# 应用名称
spring:
  application:
    name: work-hard-tool
  datasource:
    url: jdbc:mysql://localhost:3306/work-hard-tool?useUnicode=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 2
      max-active: 10
      min-idle: 0
      max-wait: 60000
      connect-timeout: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: szc
        login-password: czs
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
server:
  port: 8080

